name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: false

      - name: Add SSH Go Module Private Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

      - name: Disable checksum database for private modules
        run: |
          go env -w GOSUMDB=off

      - name: Configure Git to use SSH for private modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Clean mod cache
        run: go clean -modcache

      - name: Verify Go Modules
        run: go list -m all

      - name: Install dependencies
        run: go mod tidy && go mod download

      - name: Build project
        run: go build -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=github-actions --timeout 10m